interface=wlan0
ctrl_interface=/data/A9/smart_home/hostapd_ctrl
ctrl_interface_group=0

ssid=A9-SmartHome
hw_mode=g
channel=6
ieee80211n=1
wmm_enabled=1

wpa=2
wpa_passphrase=CHANGE_ME_BEFORE_DEPLOY
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
